name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
        
    - name: Setup .NET 7 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Pack
      run: msbuild Vortice.Mathematics.sln -t:restore,build,pack /p:Configuration=Release

    - name: Publish to NuGet
      if: github.event_name == 'push'
      run: dotnet nuget push artifacts/**/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate --source https://api.nuget.org/v3/index.json
