name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Pack
      run: dotnet pack Vortice.Mathematics.sln --configuration Release --output build/packages

    - name: Publish to NuGet
      if: github.event_name == 'push'
      run: dotnet nuget push build\packages\**\*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
          